[window]
dynamic_padding = true
decorations = "transparent"
opacity = 0.8
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 36

[scrolling]
history = 99999
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#1E1E2E' # base
foreground = '#CDD6F4' # text
dim_foreground = '#CDD6F4' # text
bright_foreground = '#CDD6F4' # text

[colors.cursor]
text = '#1E1E2E' # base
cursor = '#F5E0DC' # rosewater

[colors.vi_mode_cursor]
text = '#1E1E2E' # base
cursor = '#B4BEFE' # lavender

[colors.search.matches]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.search.focused_match]
foreground = '#1E1E2E' # base
background = '#A6E3A1' # green

[colors.footer_bar]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.hints.start]
foreground = '#1E1E2E' # base
background = '#F9E2AF' # yellow

[colors.hints.end]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.selection]
text = '#1E1E2E' # base
background = '#F5E0DC' # rosewater

[colors.normal]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1

[colors.bright]
black = '#585B70' # surface2
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#A6ADC8' # subtext0

[colors.dim]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1

[font]
size = 13

[font.normal]
family = "Lilex Nerd Font"
style = "Regular"

[font.bold]
family = "Lilex Nerd Font"
style = "Bold"

[font.italic]
family = "Lilex Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Lilex Nerd Font"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
